apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exmagnt.fullname" . }}
  labels:
    {{- include "exmagnt.labels" . | nindent 4 }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "exmagnt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "exmagnt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "exmagnt.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "exmagnt.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
#            - "--templates-namespace={{ .Values.configurations.templatesNamespace }}"
            - "--templates-namespace={{ .Release.Namespace }}"
            - "--allowed-ips={{ .Values.configurations.allowedIPs }}"
          ports:
            - name: api
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: probes
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ include "exmagnt.webhookname" . }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "exmagnt.selectorLabels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
