name: Build and publish the docker images
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  repository_dispatch:
    types:
      - deploy-staging-command

jobs:
  configure:
    name: Preliminary configuration
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.configure.outputs.ref }}
      repo-suffix: ${{ steps.configure.outputs.repo-suffix }}
      repo-push: ${{ steps.configure.outputs.repo-push }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Get version
        id: version
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
        if: |
          github.event_name == 'push' &&
          github.event.repository.full_name == github.repository &&
          startsWith(github.ref, 'refs/tags/v')

      - name: Configure
        id: configure
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          # The ref of the commit to checkout (do not use the merge commit if pull request)
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "::set-output name=ref::${{ github.event.pull_request.head.sha }}"
          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "::set-output name=ref::${{ github.event.client_payload.pull_request.head.sha }}"
          elif [[ "${{ steps.version.outputs.version }}" != "" ]]; then
            echo "::set-output name=ref::${{ steps.version.outputs.version }}"
          else
            echo "::set-output name=ref::${{ github.sha }}"
          fi

          # The suffix to append to the repository name if not triggered by a push
          [[ "${{ github.event_name }}" == "push" && "${{ github.event.repository.full_name }}" == "${{ github.repository }}" ]] && \
            echo "::set-output name=repo-suffix::" || \
            echo "::set-output name=repo-suffix::-dev"

          # Do not push the resulting images to DockerHub if triggered by a pull request or DockerHub credentials are not available
          [[ "${{ github.event_name }}" == "pull_request" || -z $DOCKER_USERNAME ]] && \
            echo "::set-output name=repo-push::false" || \
            echo "::set-output name=repo-push::true"


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: configure

    strategy:
      fail-fast: false
      matrix:
        component:
          # Operators
          - instance-operator
          - crownlabs-image-list
          - delete-stale-instances
          - tenant-operator
          - bastion-operator

          # InstanceSet tools
          - instanceset-landing

          # Exams agent
          - exmagnt

          # The new frontend
          - frontend-app
          - frontend-storybook

          # qlkube - graphQL for k8s
          - qlkube

          # SSH bastion
          - ssh-bastion

          # img-export for persistent VM instances snapshot
          - img-exporter

          # Laboratory environments
          - novnc
          - tigervnc
          - websockify
          - content-downloader
          - pycharm
          - blender
          - blender-lts

        include:
          # Operators
          - component: instance-operator
            context: ./operators
            dockerfile: ./operators/build/golang-common/Dockerfile
            build-args: COMPONENT=instance-operator
          - component: crownlabs-image-list
            context: ./operators
            dockerfile: ./operators/build/crownlabs-image-list/Dockerfile
          - component: delete-stale-instances
            context: ./operators
            dockerfile: ./operators/build/delete-stale-instances/Dockerfile
          - component: tenant-operator
            context: ./operators
            dockerfile: ./operators/build/golang-common/Dockerfile
            build-args: COMPONENT=tenant-operator
          - component: bastion-operator
            context: ./operators
            dockerfile: ./operators/build/golang-common/Dockerfile
            build-args: COMPONENT=bastion-operator

          # InstanceSet components
          - component: instanceset-landing
            context: ./operators
            dockerfile: ./operators/build/golang-common/Dockerfile
            build-args: COMPONENT=instanceset-landing

          # CrownLabs Exams Agent
          - component: exmagnt
            context: ./operators
            dockerfile: ./operators/build/golang-common/Dockerfile
            build-args: COMPONENT=exmagnt

          # The new frontend
          - component: frontend-app
            context: ./frontend
            build-args: |
              BUILD_TARGET=app
              SUBROUTE=/app
          - component: frontend-storybook
            context: ./frontend
            build-args: |
              BUILD_TARGET=storybook
              SUBROUTE=/

          # qlkube - graphQL for k8s
          - component:  qlkube
            context: ./qlkube

          # Laboratory environments
          - component: novnc
            context: ./provisioning/containers/gui-common/novnc
          - component: tigervnc
            context: ./provisioning/containers/gui-common/tigervnc
          - component: websockify
            context: ./provisioning/containers/gui-common/websockify
          - component: content-downloader
            context: ./provisioning/containers/content-downloader
          - component: pycharm
            context: ./provisioning/containers/pycharm
          - component: blender
            context: ./provisioning/containers/blender
          - component: blender-lts
            context: ./provisioning/containers/blender
            build-args: |
              BLENDER_VERSION_MAJOR=2.83
              BLENDER_VERSION_MINOR=13

          # SSH bastion
          - component: ssh-bastion
            context: ./operators/build/ssh-bastion

          # img-exporter image for InstanceSnapshot
          - component: img-exporter
            context: ./operators/build/img-exporter

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.configure.outputs.ref }}
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # The cache key is composed of the combination of the component name, the hash of the files in the build context and the hash of the commit.
          # Example: Linux-instance-operator-buildx-78702f5342c365de6dec21db1910023b19d0c56b3e3187ac860131d88ac24498-3e0fbf49898789ec0ff0f78272dd0a7703389810
          # The hash of the files in the context guarantees that a match is always found if no files of the component are modified, while the commit hash
          # guarantees uniqueness of the name, to ensure the cache is always updated (i.e. to prevent issues if the base image changes).
          key: ${{ runner.os }}-${{ matrix.component }}-buildx-${{ hashFiles(format('{0}/**', matrix.context), matrix.dockerfile) }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.component }}-buildx-${{ hashFiles(format('{0}/**', matrix.context), matrix.dockerfile) }}-
            ${{ runner.os }}-${{ matrix.component }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: needs.configure.outputs.repo-push == 'true'

      - name: Configure the build-push-action parameters
        id: parameters
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "::set-output name=repo-owner::${DOCKER_USERNAME:-crownlabs}"
          echo "::set-output name=repo-name::${{ matrix.component }}${{ needs.configure.outputs.repo-suffix }}"

          [[ -n "${{ matrix.dockerfile }}" ]] && \
            echo "::set-output name=dockerfile::${{ matrix.dockerfile }}" || \
            echo "::set-output name=dockerfile::${{ matrix.context }}/Dockerfile"

      - name: Build and Push the ${{ matrix.component }} image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ${{ steps.parameters.outputs.repo-owner }}/${{ steps.parameters.outputs.repo-name }}:latest
            ${{ steps.parameters.outputs.repo-owner }}/${{ steps.parameters.outputs.repo-name }}:${{ needs.configure.outputs.ref }}
          push: ${{ needs.configure.outputs.repo-push }}
          file: ${{ steps.parameters.outputs.dockerfile }}
          context: ${{ matrix.context }}
          build-args: ${{ matrix.build-args }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temporary fix, to prevent the cache from continuing growing
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  trigger-events-master:
    name: Trigger events upon successful push to master
    runs-on: ubuntu-latest
    needs:
      - configure
      - build
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master' &&
      needs.configure.outputs.repo-push == 'true'

    steps:
      - name: Send the Slack notification
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          author_name: CrownLabs CI
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()

      - name: Notify Event to CrownOps
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: netgroup-polito/CrownOps
          event-type: preprod-event
          client-payload: '{"tag": "${{ needs.configure.outputs.ref }}"}'

  trigger-events-deploy-staging:
    name: Trigger events upon /deploy-staging comment
    runs-on: ubuntu-latest
    needs:
      - configure
      - build
    if: |
      github.event_name == 'repository_dispatch' &&
      needs.configure.outputs.repo-push == 'true'

    steps:
      - name: Notify Event to CrownOps
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: netgroup-polito/CrownOps
          event-type: deploy-staging-event
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "pr-number": "${{ github.event.client_payload.github.payload.issue.number }}",
              "tag": "${{ needs.configure.outputs.ref }}"
            }

      - name: Report status as reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: "hooray"

  release:
    name: Create a new CrownLabs release
    runs-on: ubuntu-latest
    needs:
      - configure
      - build
    if: |
      needs.configure.outputs.version != '' &&
      needs.configure.outputs.repo-push == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.configure.outputs.ref }}
          # The changelog generation requires the entire history
          fetch-depth: 0
          persist-credentials: false

      - name: Get the latest CrownLabs release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        id: last-release
        with:
          repository: ${{ github.repository }}

      - name: Generate the CHANGELOG
        uses: RiskLedger/generate-changelog@v1.2
        id: changelog
        with:
          from: ${{ steps.last-release.outputs.release }}
          to: ${{ needs.configure.outputs.version }}
        env:
          GITHUB_AUTH: ${{ secrets.CI_TOKEN }}

      - name: Save the CHANGELOG as a file
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > ./CHANGELOG.md
          sed -i "1s/.*/## Changes since ${{ steps.last-release.outputs.release }}/" ./CHANGELOG.md

      - name: Create the release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.configure.outputs.version }}
          release_name: Release ${{ needs.configure.outputs.version }}
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Notify Event to CrownOps
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: netgroup-polito/CrownOps
          event-type: release-event
          client-payload: '{"version": "${{ needs.configure.outputs.version }}"}'
